Send subscription e-mails after creating/updating events
kartevonmorgen/openfairdb pull request #240
Opened 2020-01-20 13:20 UTC by uklotzde

The final step after finishing the preceding refactoring and extensions.

Wording: "Event" = "Veranstaltung"

2020-01-20 14:37 UTC, flosse approved these changes

2020-01-20 15:13 UTC, wellemut requested changes
Danke @uklotzde

2020-01-20 15:13 UTC, wellemut commented on src/adapters/user_communication.rs
> +    let subject = format!("Karte von morgen - neue Veranstaltung: {}", event.title);
Karte von morgen steht bereits im Absender und muss daher nicht so prominent in das Subject
"Kvm - neues Event:  {}", event.title
reich daher voll aus. Event heißen Veranstaltungen sowieso auch schon auf der Deutschen karte.

2020-01-20 15:13 UTC, wellemut commented on src/adapters/user_communication.rs
> +        "Karte von morgen - aktualisierte Veranstaltung: {}",
Gleicher Punkt wie oben, Subject muss nicht so lang sein sonder
"Kvm - Event verändert: {}" (Und danach Titel des Events)

2020-01-20 15:13 UTC, wellemut commented on src/adapters/user_communication.rs
> +Du kannst dein Abonnement des Kartenbereichs abbestellen indem du dich auf https://kartevonmorgen.org einloggst.\n
Bitte nehmt noch folgenden Satz mit auf:
"Weitere Hinweise und Tricks zur Nutzung, wie du interaktive Karten per IFrame auf deiner Webseite einbettest oder Papierkarten erstellst, findest du hier: https://blog.vonmorgen.org"

2020-01-20 15:13 UTC, wellemut commented on src/adapters/user_communication.rs
> +Du kannst dein Abonnement des Kartenbereichs abbestellen indem du dich auf https://kartevonmorgen.org einloggst.\n
Für Einträge kann der gleiche Satz natürlich auch mitgeschickt werden (Zeile 90)

2020-01-20 15:13 UTC, wellemut commented on src/adapters/user_communication.rs
> +        "Karte von morgen - aktualisierte Veranstaltung: {}",
Bei Places könnte es natürlich equivalent heißen (Zeile 60)
Kvm - Eintrag verändert

2020-01-20 15:13 UTC, wellemut commented on src/adapters/user_communication.rs
> +    let subject = format!("Karte von morgen - neue Veranstaltung: {}", event.title);
Bei Places könnte es natürlich equivalent heißen (Zeile 52) 
Kvm - neuer Eintrag

2020-01-20 18:34 UTC, uklotzde commented on src/adapters/user_communication.rs
> +    let subject = format!("Karte von morgen - neue Veranstaltung: {}", event.title);
"das" oder "der" Event? Denglisch führt leider zu diesen Verwirrungen.

2020-01-20 19:37 UTC, uklotzde commented on src/adapters/user_communication.rs
> +    let subject = format!("Karte von morgen - neue Veranstaltung: {}", event.title);
Pragmatische Lösung: Es bleibt bei "Eintrag" für beide Fälle. Erst im Text folgt die Unterscheidung.

2020-01-20 20:46 UTC, merged

2020-01-21 22:07 UTC, wellemut commented
Sehr cool! Danke dir Uwe
Kürzer sieht wirklich besser aus in den Mails:
![grafik](https://user-images.githubusercontent.com/15019030/72847400-bfe44c80-3ca2-11ea-956c-7a9d5c131871.png)