Duplicates
kartevonmorgen/openfairdb pull request #25
Opened 2016-09-18 12:42 UTC by ziedavid

First attempt to detect duplicates (#20)

2016-09-18 18:57 UTC, flosse commented on src/main.rs
> +
please remove empty lines

2016-09-18 18:58 UTC, flosse commented on src/search.rs
> +  levenshtein_distance_small(&e1.title, &e2.title, maxDist) | (words_equal_except_k_words(&e1.title, &e2.title, maxWordsDifferent))
please use `||` instead of `|`

2016-09-18 19:00 UTC, flosse requested changes
I'm looking forward :)

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +pub fn find_duplicates(entries: &Vec<Entry>) -> Vec<(&Entry, &Entry, &str)> {
I'd return just the IDs and the DuplicateType

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +fn in_close_proximity(e1: &Entry, e2: &Entry, maxDistMeters:u32) -> bool{
use `max_dist_meters` instead of `maxDistMeters`

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +      println!("lat1: {}, lat2: {}, lng1: {}, lng2: {} --> distance: {} m (near)", e1.lat, e2.lat, e1.lng, e2.lng, dist);
use `debug!` or just remove it

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +  if hamming_distance_small(&e1.title, &e2.title, maxDist) | (words_equal_except_k_words(&e1.title, &e2.title, maxWordsDifferent)) {
you don't need the `if`...`else` construct :)
..and use `||` instead of `|`

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +  if dist > maxDist{
you don't need the `if` .. `else` construct :)

2016-09-18 19:00 UTC, flosse commented on src/main.rs
> +              let duplicates : Vec<(&Entry, &Entry, &str)> = search::find_duplicates(&entries);  // vec!();
I think you can drop the type definition

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +// returns 3 if they are located within 10 meters of each other
I think these comments are out of date ;-)

2016-09-18 19:00 UTC, flosse commented on src/search.rs
> +use std::f64::consts;
`consts` can be dropped

2016-09-21 08:23 UTC, ziedavid commented
thanks for the comments! I learned something from it :)

I made one other change: I noticed that for levenshtein-distance I earlier copied the naive algorithm from wikipedia. That calculates distances over and over again. Now I implemented the dynamic programming version, which is faster. It's still not as fast as hamming-distance (it takes up to 10 seconds for the whole dataset) but I guess that's more or less acceptable. Levenshtein-distance is better to capture small typos or so. E.g. "a12345" and "12345" have hamming-distance 6 but levenshtein-distance 1.

2016-09-21 20:22 UTC, flosse commented
I like the levenshtein distance :) 
And i think there are good chances to speed up the calculation. But even if not, it doesn't matter because this method will be called once a week or month, so we shouldn't care too much ;-)

2016-09-21 20:26 UTC, flosse commented
...moreover we could use both: e.g. the web app calls `/entries/duplicates?type=simple` for the first run and presents it to the user. Meanwhile a second call `/entries/duplicates?type=precise` gets fired to improve the results.

2016-09-22 22:39 UTC, flosse commented
I think we could merge this soon.
Would you mind to rebase your PR into one commit?

2016-09-28 21:29 UTC, flosse approved these changes

2016-09-28 21:30 UTC, merged