Add clearance center app
kartevonmorgen/openfairdb pull request #292
Opened 2020-08-20 11:09 UTC by flosse

2020-08-20 17:08 UTC, uklotzde requested changes
The Docker build needs to be updated

2020-08-21 07:32 UTC, uklotzde approved these changes

2020-08-21 07:32 UTC, merged

2020-08-24 15:10 UTC, flosse commented
I created a PR (https://github.com/rustwasm/wasm-pack/pull/906) that would allow to build the app artifacts within the main `target` directory by using the `--target-dir` option

2020-08-24 15:19 UTC, flosse commented
Related issue: https://github.com/rust-lang/cargo/issues/7004