Api errors
kartevonmorgen/openfairdb pull request #353
Opened 2021-08-04 13:25 UTC by magdaddy

2021-08-04 15:05 UTC, uklotzde commented
The CI build builds each sub-crate in isolation. This is different from building the whole workspace and might detect errors in the sub-crates.

Please fix and then force push.

2021-08-04 15:15 UTC, flosse requested changes

2021-08-04 15:15 UTC, flosse commented on src/ports/web/api/mod.rs
> +                        // }
Please either delete this or add a TODO comment with some explanations.

2021-08-04 17:13 UTC, magdaddy commented
After implementing `From<Url> for String` and fixing countless clippy warnings (all of which, by the way, have nothing to do with my PR whatsoever) now clippy gives this:

```
error: couldn't read src/ports/web/frontend/../../../../ofdb-app-clearance/pkg/clearance.js: No such file or directory (os error 2)
  --> src/ports/web/frontend/mod.rs:33:28
   |
33 | const CLEARANCE_JS: &str = include_str!("../../../../ofdb-app-clearance/pkg/clearance.js");
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: couldn't read src/ports/web/frontend/../../../../ofdb-app-clearance/pkg/clearance_bg.wasm: No such file or directory (os error 2)
  --> src/ports/web/frontend/mod.rs:35:5
   |
35 |     include_bytes!("../../../../ofdb-app-clearance/pkg/clearance_bg.wasm");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `include_bytes` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
```

I have no idea how to fix this, but I get a faint memory that you once had something like this @flosse ?

2021-08-05 08:07 UTC, flosse commented
That's wired I can't reproduce this locally...

2021-08-05 08:13 UTC, flosse approved these changes

2021-08-05 08:13 UTC, flosse commented
... I think we can ignore the clippy warnings for now.

2021-08-05 08:18 UTC, merged